// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protectorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BruteforceProtectorServiceClient is the client API for BruteforceProtectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BruteforceProtectorServiceClient interface {
	Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
	ResetLogin(ctx context.Context, in *ResetLoginLimitRequest, opts ...grpc.CallOption) (*ResetLoginLimitResponse, error)
	ResetIP(ctx context.Context, in *ResetIPLimitRequest, opts ...grpc.CallOption) (*ResetIPLimitResponse, error)
	AddBlackListItem(ctx context.Context, in *AddAccessListRequest, opts ...grpc.CallOption) (*AddAccessListResponse, error)
	RemoveBlackListItem(ctx context.Context, in *RemoveAccessListRequest, opts ...grpc.CallOption) (*RemoveAccessListResponse, error)
	GetBlackListItems(ctx context.Context, in *GetAccessListItemsRequest, opts ...grpc.CallOption) (*GetAccessListItemsResponse, error)
	AddWhiteListItem(ctx context.Context, in *AddAccessListRequest, opts ...grpc.CallOption) (*AddAccessListResponse, error)
	RemoveWhiteListItem(ctx context.Context, in *RemoveAccessListRequest, opts ...grpc.CallOption) (*RemoveAccessListResponse, error)
	GetWhiteListItems(ctx context.Context, in *GetAccessListItemsRequest, opts ...grpc.CallOption) (*GetAccessListItemsResponse, error)
}

type bruteforceProtectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBruteforceProtectorServiceClient(cc grpc.ClientConnInterface) BruteforceProtectorServiceClient {
	return &bruteforceProtectorServiceClient{cc}
}

func (c *bruteforceProtectorServiceClient) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, "/bruteforceprotector.BruteforceProtectorService/Verify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bruteforceProtectorServiceClient) ResetLogin(ctx context.Context, in *ResetLoginLimitRequest, opts ...grpc.CallOption) (*ResetLoginLimitResponse, error) {
	out := new(ResetLoginLimitResponse)
	err := c.cc.Invoke(ctx, "/bruteforceprotector.BruteforceProtectorService/ResetLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bruteforceProtectorServiceClient) ResetIP(ctx context.Context, in *ResetIPLimitRequest, opts ...grpc.CallOption) (*ResetIPLimitResponse, error) {
	out := new(ResetIPLimitResponse)
	err := c.cc.Invoke(ctx, "/bruteforceprotector.BruteforceProtectorService/ResetIP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bruteforceProtectorServiceClient) AddBlackListItem(ctx context.Context, in *AddAccessListRequest, opts ...grpc.CallOption) (*AddAccessListResponse, error) {
	out := new(AddAccessListResponse)
	err := c.cc.Invoke(ctx, "/bruteforceprotector.BruteforceProtectorService/AddBlackListItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bruteforceProtectorServiceClient) RemoveBlackListItem(ctx context.Context, in *RemoveAccessListRequest, opts ...grpc.CallOption) (*RemoveAccessListResponse, error) {
	out := new(RemoveAccessListResponse)
	err := c.cc.Invoke(ctx, "/bruteforceprotector.BruteforceProtectorService/RemoveBlackListItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bruteforceProtectorServiceClient) GetBlackListItems(ctx context.Context, in *GetAccessListItemsRequest, opts ...grpc.CallOption) (*GetAccessListItemsResponse, error) {
	out := new(GetAccessListItemsResponse)
	err := c.cc.Invoke(ctx, "/bruteforceprotector.BruteforceProtectorService/GetBlackListItems", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bruteforceProtectorServiceClient) AddWhiteListItem(ctx context.Context, in *AddAccessListRequest, opts ...grpc.CallOption) (*AddAccessListResponse, error) {
	out := new(AddAccessListResponse)
	err := c.cc.Invoke(ctx, "/bruteforceprotector.BruteforceProtectorService/AddWhiteListItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bruteforceProtectorServiceClient) RemoveWhiteListItem(ctx context.Context, in *RemoveAccessListRequest, opts ...grpc.CallOption) (*RemoveAccessListResponse, error) {
	out := new(RemoveAccessListResponse)
	err := c.cc.Invoke(ctx, "/bruteforceprotector.BruteforceProtectorService/RemoveWhiteListItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bruteforceProtectorServiceClient) GetWhiteListItems(ctx context.Context, in *GetAccessListItemsRequest, opts ...grpc.CallOption) (*GetAccessListItemsResponse, error) {
	out := new(GetAccessListItemsResponse)
	err := c.cc.Invoke(ctx, "/bruteforceprotector.BruteforceProtectorService/GetWhiteListItems", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BruteforceProtectorServiceServer is the server API for BruteforceProtectorService service.
// All implementations must embed UnimplementedBruteforceProtectorServiceServer
// for forward compatibility
type BruteforceProtectorServiceServer interface {
	Verify(context.Context, *VerifyRequest) (*VerifyResponse, error)
	ResetLogin(context.Context, *ResetLoginLimitRequest) (*ResetLoginLimitResponse, error)
	ResetIP(context.Context, *ResetIPLimitRequest) (*ResetIPLimitResponse, error)
	AddBlackListItem(context.Context, *AddAccessListRequest) (*AddAccessListResponse, error)
	RemoveBlackListItem(context.Context, *RemoveAccessListRequest) (*RemoveAccessListResponse, error)
	GetBlackListItems(context.Context, *GetAccessListItemsRequest) (*GetAccessListItemsResponse, error)
	AddWhiteListItem(context.Context, *AddAccessListRequest) (*AddAccessListResponse, error)
	RemoveWhiteListItem(context.Context, *RemoveAccessListRequest) (*RemoveAccessListResponse, error)
	GetWhiteListItems(context.Context, *GetAccessListItemsRequest) (*GetAccessListItemsResponse, error)
	mustEmbedUnimplementedBruteforceProtectorServiceServer()
}

// UnimplementedBruteforceProtectorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBruteforceProtectorServiceServer struct {
}

func (UnimplementedBruteforceProtectorServiceServer) Verify(context.Context, *VerifyRequest) (*VerifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedBruteforceProtectorServiceServer) ResetLogin(context.Context, *ResetLoginLimitRequest) (*ResetLoginLimitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetLogin not implemented")
}
func (UnimplementedBruteforceProtectorServiceServer) ResetIP(context.Context, *ResetIPLimitRequest) (*ResetIPLimitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetIP not implemented")
}
func (UnimplementedBruteforceProtectorServiceServer) AddBlackListItem(context.Context, *AddAccessListRequest) (*AddAccessListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBlackListItem not implemented")
}
func (UnimplementedBruteforceProtectorServiceServer) RemoveBlackListItem(context.Context, *RemoveAccessListRequest) (*RemoveAccessListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveBlackListItem not implemented")
}
func (UnimplementedBruteforceProtectorServiceServer) GetBlackListItems(context.Context, *GetAccessListItemsRequest) (*GetAccessListItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlackListItems not implemented")
}
func (UnimplementedBruteforceProtectorServiceServer) AddWhiteListItem(context.Context, *AddAccessListRequest) (*AddAccessListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddWhiteListItem not implemented")
}
func (UnimplementedBruteforceProtectorServiceServer) RemoveWhiteListItem(context.Context, *RemoveAccessListRequest) (*RemoveAccessListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveWhiteListItem not implemented")
}
func (UnimplementedBruteforceProtectorServiceServer) GetWhiteListItems(context.Context, *GetAccessListItemsRequest) (*GetAccessListItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWhiteListItems not implemented")
}
func (UnimplementedBruteforceProtectorServiceServer) mustEmbedUnimplementedBruteforceProtectorServiceServer() {
}

// UnsafeBruteforceProtectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BruteforceProtectorServiceServer will
// result in compilation errors.
type UnsafeBruteforceProtectorServiceServer interface {
	mustEmbedUnimplementedBruteforceProtectorServiceServer()
}

func RegisterBruteforceProtectorServiceServer(s grpc.ServiceRegistrar, srv BruteforceProtectorServiceServer) {
	s.RegisterService(&BruteforceProtectorService_ServiceDesc, srv)
}

func _BruteforceProtectorService_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BruteforceProtectorServiceServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bruteforceprotector.BruteforceProtectorService/Verify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BruteforceProtectorServiceServer).Verify(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BruteforceProtectorService_ResetLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetLoginLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BruteforceProtectorServiceServer).ResetLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bruteforceprotector.BruteforceProtectorService/ResetLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BruteforceProtectorServiceServer).ResetLogin(ctx, req.(*ResetLoginLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BruteforceProtectorService_ResetIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetIPLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BruteforceProtectorServiceServer).ResetIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bruteforceprotector.BruteforceProtectorService/ResetIP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BruteforceProtectorServiceServer).ResetIP(ctx, req.(*ResetIPLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BruteforceProtectorService_AddBlackListItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAccessListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BruteforceProtectorServiceServer).AddBlackListItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bruteforceprotector.BruteforceProtectorService/AddBlackListItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BruteforceProtectorServiceServer).AddBlackListItem(ctx, req.(*AddAccessListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BruteforceProtectorService_RemoveBlackListItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAccessListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BruteforceProtectorServiceServer).RemoveBlackListItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bruteforceprotector.BruteforceProtectorService/RemoveBlackListItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BruteforceProtectorServiceServer).RemoveBlackListItem(ctx, req.(*RemoveAccessListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BruteforceProtectorService_GetBlackListItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccessListItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BruteforceProtectorServiceServer).GetBlackListItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bruteforceprotector.BruteforceProtectorService/GetBlackListItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BruteforceProtectorServiceServer).GetBlackListItems(ctx, req.(*GetAccessListItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BruteforceProtectorService_AddWhiteListItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAccessListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BruteforceProtectorServiceServer).AddWhiteListItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bruteforceprotector.BruteforceProtectorService/AddWhiteListItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BruteforceProtectorServiceServer).AddWhiteListItem(ctx, req.(*AddAccessListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BruteforceProtectorService_RemoveWhiteListItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAccessListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BruteforceProtectorServiceServer).RemoveWhiteListItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bruteforceprotector.BruteforceProtectorService/RemoveWhiteListItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BruteforceProtectorServiceServer).RemoveWhiteListItem(ctx, req.(*RemoveAccessListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BruteforceProtectorService_GetWhiteListItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccessListItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BruteforceProtectorServiceServer).GetWhiteListItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bruteforceprotector.BruteforceProtectorService/GetWhiteListItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BruteforceProtectorServiceServer).GetWhiteListItems(ctx, req.(*GetAccessListItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BruteforceProtectorService_ServiceDesc is the grpc.ServiceDesc for BruteforceProtectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BruteforceProtectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bruteforceprotector.BruteforceProtectorService",
	HandlerType: (*BruteforceProtectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Verify",
			Handler:    _BruteforceProtectorService_Verify_Handler,
		},
		{
			MethodName: "ResetLogin",
			Handler:    _BruteforceProtectorService_ResetLogin_Handler,
		},
		{
			MethodName: "ResetIP",
			Handler:    _BruteforceProtectorService_ResetIP_Handler,
		},
		{
			MethodName: "AddBlackListItem",
			Handler:    _BruteforceProtectorService_AddBlackListItem_Handler,
		},
		{
			MethodName: "RemoveBlackListItem",
			Handler:    _BruteforceProtectorService_RemoveBlackListItem_Handler,
		},
		{
			MethodName: "GetBlackListItems",
			Handler:    _BruteforceProtectorService_GetBlackListItems_Handler,
		},
		{
			MethodName: "AddWhiteListItem",
			Handler:    _BruteforceProtectorService_AddWhiteListItem_Handler,
		},
		{
			MethodName: "RemoveWhiteListItem",
			Handler:    _BruteforceProtectorService_RemoveWhiteListItem_Handler,
		},
		{
			MethodName: "GetWhiteListItems",
			Handler:    _BruteforceProtectorService_GetWhiteListItems_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/api.proto",
}
