name: Go

on:
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Build
        working-directory: ${{ github.head_ref }}
        run: go build -v ./...

      - name: Unit tests
        working-directory: ${{ github.head_ref }}
        run: go test -gcflags=-l -v ./...

      - name: Optimization tests
        working-directory: ${{ github.head_ref }}
        run: go test -gcflags=-l -v -count=1 -timeout=30s -tags bench ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.32.1
          args: --timeout=5m -v
          working-directory: ${{ github.head_ref }}